[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.29"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
